export { About } from './sections/About'
export { Contact } from './sections/Contact'
export { Gallery } from './sections/Gallery'
export { Header } from './Header'
export { Main } from './Main'
export { Projects } from './sections/Projects'
